// <auto-generated />
using System;
using Fota.DataLayer.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fota.DataLayer.Migrations
{
    [DbContext(typeof(FOTADbContext))]
    [Migration("20251124163849_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fota.DataLayer.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sarah.johnson@fotasystem.com",
                            IsActive = true,
                            Name = "Sarah Johnson",
                            PhoneNumber = "+201234567890"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.hassan@fotasystem.com",
                            IsActive = true,
                            Name = "Ahmed Hassan",
                            PhoneNumber = "+201234567891"
                        });
                });

            modelBuilder.Entity("Fota.DataLayer.Models.Diagnostic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedByAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToDeveloperId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByAdminId");

                    b.HasIndex("AssignedToDeveloperId");

                    b.HasIndex("SubscriberId");

                    b.HasIndex("TopicId");

                    b.ToTable("Diagnostics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedByAdminId = 1,
                            AssignedToDeveloperId = 2,
                            CreatedAt = new DateTime(2024, 5, 20, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Description = "Battery pack temperature exceeding normal range in test vehicle VIN:ABC123",
                            Priority = "High",
                            Status = "InProgress",
                            SubscriberId = 2,
                            Title = "Battery Temperature Warning",
                            TopicId = 2
                        });
                });

            modelBuilder.Entity("Fota.DataLayer.Models.DiagnosticSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<int>("DiagnosticId")
                        .HasColumnType("int");

                    b.Property<byte[]>("HexFileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HexFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("DiagnosticId");

                    b.ToTable("DiagnosticSolutions");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.MessageDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFailed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("SubscriberId");

                    b.ToTable("MessageDeliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            DeliveredAt = new DateTime(2024, 5, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelivered = true,
                            IsFailed = false,
                            IsRead = true,
                            MessageId = 1,
                            ReadAt = new DateTime(2024, 5, 10, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 1
                        });
                });

            modelBuilder.Entity("Fota.DataLayer.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("LeadId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByAdminId = 1,
                            Description = "Responsible for engine control updates",
                            IsActive = true,
                            LeadId = 1,
                            Name = "ECU Development Team"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedByAdminId = 1,
                            Description = "Handles BMS firmware development",
                            IsActive = true,
                            LeadId = 2,
                            Name = "Battery Systems Team"
                        });
                });

            modelBuilder.Entity("Fota.DataLayer.Models.TeamDeveloper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamDevelopers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = 1,
                            IsActive = true,
                            JoinedAt = new DateTime(2024, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Lead",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = 3,
                            IsActive = true,
                            JoinedAt = new DateTime(2024, 3, 12, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Senior",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DeveloperId = 2,
                            IsActive = true,
                            JoinedAt = new DateTime(2024, 3, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Role = "Lead",
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("Fota.DataLayer.Models.TeamTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TopicId");

                    b.ToTable("TeamTopics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            TeamId = 1,
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            TeamId = 2,
                            TopicId = 2
                        });
                });

            modelBuilder.Entity("Fota.DataLayer.Models.TopicSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriberId")
                        .HasColumnType("int");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnsubscribedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriberId");

                    b.HasIndex("TopicId");

                    b.ToTable("TopicSubscribers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SubscribedAt = new DateTime(2024, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 1,
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            SubscribedAt = new DateTime(2024, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriberId = 2,
                            TopicId = 2
                        });
                });

            modelBuilder.Entity("Fota.Models.BaseMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("HexFileContent")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("HexFileName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.Property<int>("UploaderId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.HasIndex("TopicId");

                    b.HasIndex("UploaderId");

                    b.ToTable("BaseMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ECU Firmware Update v2.3.1 - Performance improvements",
                            HexFileName = "ecu_v2.3.1.hex",
                            IsDeleted = false,
                            MessageType = "Standard",
                            PublishedAt = new DateTime(2024, 5, 10, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            PublisherId = 1,
                            Status = "Published",
                            TopicId = 1,
                            UploaderId = 1,
                            Version = "2.3.1"
                        },
                        new
                        {
                            Id = 2,
                            ApprovedAt = new DateTime(2024, 5, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2024, 5, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "BMS Critical Security Patch v1.8.2",
                            HexFileName = "bms_v1.8.2_security.hex",
                            IsDeleted = false,
                            MessageType = "Standard",
                            Status = "Approved",
                            TopicId = 2,
                            UploaderId = 2,
                            Version = "1.8.2"
                        });
                });

            modelBuilder.Entity("Fota.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mohamed.ali@fotasystem.com",
                            IsActive = true,
                            Name = "Mohamed Ali",
                            PhoneNumber = "+201234567892"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatima.nour@fotasystem.com",
                            IsActive = true,
                            Name = "Fatima Nour",
                            PhoneNumber = "+201234567893"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.khaled@fotasystem.com",
                            IsActive = true,
                            Name = "Omar Khaled",
                            PhoneNumber = "+201234567894"
                        });
                });

            modelBuilder.Entity("Fota.Models.Subscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Subscribers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fleet.cairo@toyota-eg.com",
                            IsActive = true,
                            Name = "Toyota Fleet - Cairo",
                            PhoneNumber = "+201234567895"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 4, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "test.center@bmw-eg.com",
                            IsActive = true,
                            Name = "BMW Test Center",
                            PhoneNumber = "+201234567896"
                        });
                });

            modelBuilder.Entity("Fota.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "ECU firmware updates and diagnostics",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Engine Control Unit"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "BMS firmware for electric vehicles",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Battery Management System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Navigation and multimedia updates",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Infotainment System"
                        });
                });

            modelBuilder.Entity("Fota.DataLayer.Models.Diagnostic", b =>
                {
                    b.HasOne("Fota.DataLayer.Models.Admin", "AssignedByAdmin")
                        .WithMany("AssignedDiagnostics")
                        .HasForeignKey("AssignedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fota.Models.Developer", "AssignedToDeveloper")
                        .WithMany("AssignedDiagnostics")
                        .HasForeignKey("AssignedToDeveloperId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fota.Models.Subscriber", "Subscriber")
                        .WithMany("Diagnostics")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fota.Models.Topic", "Topic")
                        .WithMany("Diagnostics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssignedByAdmin");

                    b.Navigation("AssignedToDeveloper");

                    b.Navigation("Subscriber");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.DiagnosticSolution", b =>
                {
                    b.HasOne("Fota.Models.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fota.DataLayer.Models.Diagnostic", "Diagnostic")
                        .WithMany("Solutions")
                        .HasForeignKey("DiagnosticId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Diagnostic");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.MessageDelivery", b =>
                {
                    b.HasOne("Fota.Models.BaseMessage", "Message")
                        .WithMany("Deliveries")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fota.Models.Subscriber", "Subscriber")
                        .WithMany("MessageDeliveries")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.Team", b =>
                {
                    b.HasOne("Fota.DataLayer.Models.Admin", "CreatedByAdmin")
                        .WithMany("CreatedTeams")
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fota.Models.Developer", "Lead")
                        .WithMany("LeadingTeams")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByAdmin");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.TeamDeveloper", b =>
                {
                    b.HasOne("Fota.Models.Developer", "Developer")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fota.DataLayer.Models.Team", "Team")
                        .WithMany("TeamDevelopers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.TeamTopic", b =>
                {
                    b.HasOne("Fota.DataLayer.Models.Team", "Team")
                        .WithMany("TeamTopics")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fota.Models.Topic", "Topic")
                        .WithMany("TeamTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.TopicSubscriber", b =>
                {
                    b.HasOne("Fota.Models.Subscriber", "Subscriber")
                        .WithMany("TopicSubscriptions")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fota.Models.Topic", "Topic")
                        .WithMany("TopicSubscribers")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subscriber");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Fota.Models.BaseMessage", b =>
                {
                    b.HasOne("Fota.Models.Developer", "Publisher")
                        .WithMany("PublishedMessages")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Fota.Models.Topic", "Topic")
                        .WithMany("Messages")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Fota.Models.Developer", "Uploader")
                        .WithMany("UploadedMessages")
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Topic");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.Admin", b =>
                {
                    b.Navigation("AssignedDiagnostics");

                    b.Navigation("CreatedTeams");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.Diagnostic", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Fota.DataLayer.Models.Team", b =>
                {
                    b.Navigation("TeamDevelopers");

                    b.Navigation("TeamTopics");
                });

            modelBuilder.Entity("Fota.Models.BaseMessage", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("Fota.Models.Developer", b =>
                {
                    b.Navigation("AssignedDiagnostics");

                    b.Navigation("LeadingTeams");

                    b.Navigation("PublishedMessages");

                    b.Navigation("TeamMemberships");

                    b.Navigation("UploadedMessages");
                });

            modelBuilder.Entity("Fota.Models.Subscriber", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("MessageDeliveries");

                    b.Navigation("TopicSubscriptions");
                });

            modelBuilder.Entity("Fota.Models.Topic", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("Messages");

                    b.Navigation("TeamTopics");

                    b.Navigation("TopicSubscribers");
                });
#pragma warning restore 612, 618
        }
    }
}
